<?php
/** @var Magento\Backend\Block\Template $block */

/** @var Boostsales\CustomCheckout\Model\Data\Invoice $invoiceEmail */

$invoiceEmail = $block->getInvoiceEmail($block->getOrder());
$poNumber =   $block->getPoNumber($block->getOrder());

if($invoiceEmail || $poNumber):
?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Other information') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="order-information">
        <?php if($invoiceEmail){?>
            <div class="box">
                <strong
                    class="box-title"><span><?php /* @escapeNotVerified */ echo __('Invoice Email Address') ?></span></strong>
                <div class="box-content">
                    <?php echo $this->escapeHtml($invoiceEmail); ?>
                </div>
            </div>
            <?php } ?>
            <?php if($poNumber){?>
            <div class="box">
                <strong
                    class="box-title"><span><?php /* @escapeNotVerified */ echo __('PO Number') ?></span></strong>
                <div class="box-content">
                    <?php echo $this->escapeHtml($poNumber); ?>
                </div>
            </div>
            <?php }?>
        </div>
    </div>
</section>
<?php endif;?>